In [46]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('train.csv')

In [6]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [18]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [20]:
df.drop(columns = ['PassengerId', 'Pclass', 'Name'], inplace=True)

In [22]:
df.shape

(891, 9)

In [24]:
df.isnull().sum()

Survived      0
Sex           0
Age         177
SibSp         0
Parch         0
Ticket        0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [28]:
df.duplicated().sum()

15

In [32]:
df['Survived'].isnull().sum()

0

In [34]:
df

Survived     Sex   Age  SibSp  Parch            Ticket     Fare Cabin  \
0           0    male  22.0      1      0         A/5 21171   7.2500   NaN   
1           1  female  38.0      1      0          PC 17599  71.2833   C85   
2           1  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN   
3           1  female  35.0      1      0            113803  53.1000  C123   
4           0    male  35.0      0      0            373450   8.0500   NaN   
..        ...     ...   ...    ...    ...               ...      ...   ...   
886         0    male  27.0      0      0            211536  13.0000   NaN   
887         1  female  19.0      0      0            112053  30.0000   B42   
888         0  female   NaN      1      2        W./C. 6607  23.4500   NaN   
889         1    male  26.0      0      0            111369  30.0000  C148   
890         0    male  32.0      0      0            370376   7.7500   NaN   

    Embarked  
0          S  
1          C  
2          S  
3          S  
4          S  
..       ...  
886        S  
887        S  
888        S  
889        C  
890        Q  

[891 rows x 9 columns]

In [36]:
df['Sex'] = df['Sex'].apply(lambda x:1 if 'male' in x else 0)

In [38]:
df['Sex']

0      1
1      1
2      1
3      1
4      1
      ..
886    1
887    1
888    1
889    1
890    1
Name: Sex, Length: 891, dtype: int64

In [42]:
df['Age'].unique()

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [52]:
df['Age'] = df['Age'].fillna(np.mean(df['Age']))

In [54]:
df['Age'].unique()

array([22.        , 38.        , 26.        , 35.        , 29.69911765,
       54.        ,  2.        , 27.        , 14.        ,  4.        ,
       58.        , 20.        , 39.        , 55.        , 31.        ,
       34.        , 15.        , 28.        ,  8.        , 19.        ,
       40.        , 66.        , 42.        , 21.        , 18.        ,
        3.        ,  7.        , 49.        , 29.        , 65.        ,
       28.5       ,  5.        , 11.        , 45.        , 17.        ,
       32.        , 16.        , 25.        ,  0.83      , 30.        ,
       33.        , 23.        , 24.        , 46.        , 59.        ,
       71.        , 37.        , 47.        , 14.5       , 70.5       ,
       32.5       , 12.        ,  9.        , 36.5       , 51.        ,
       55.5       , 40.5       , 44.        ,  1.        , 61.        ,
       56.        , 50.        , 36.        , 45.5       , 20.5       ,
       62.        , 41.        , 52.        , 63.        , 23.5 

In [58]:
df['SibSp'].unique()

array([1, 0, 3, 4, 2, 5, 8], dtype=int64)

In [60]:
df

Survived  Sex        Age  SibSp  Parch            Ticket     Fare Cabin  \
0           0    1  22.000000      1      0         A/5 21171   7.2500   NaN   
1           1    1  38.000000      1      0          PC 17599  71.2833   C85   
2           1    1  26.000000      0      0  STON/O2. 3101282   7.9250   NaN   
3           1    1  35.000000      1      0            113803  53.1000  C123   
4           0    1  35.000000      0      0            373450   8.0500   NaN   
..        ...  ...        ...    ...    ...               ...      ...   ...   
886         0    1  27.000000      0      0            211536  13.0000   NaN   
887         1    1  19.000000      0      0            112053  30.0000   B42   
888         0    1  29.699118      1      2        W./C. 6607  23.4500   NaN   
889         1    1  26.000000      0      0            111369  30.0000  C148   
890         0    1  32.000000      0      0            370376   7.7500   NaN   

    Embarked  
0          S  
1          C  
2          S  
3          S  
4          S  
..       ...  
886        S  
887        S  
888        S  
889        C  
890        Q  

[891 rows x 9 columns]

In [64]:
df['Parch'].unique()

array([0, 1, 2, 5, 3, 4, 6], dtype=int64)

In [66]:
df.drop(columns = 'Ticket' ,inplace=True)

In [68]:
df

Survived  Sex        Age  SibSp  Parch     Fare Cabin Embarked
0           0    1  22.000000      1      0   7.2500   NaN        S
1           1    1  38.000000      1      0  71.2833   C85        C
2           1    1  26.000000      0      0   7.9250   NaN        S
3           1    1  35.000000      1      0  53.1000  C123        S
4           0    1  35.000000      0      0   8.0500   NaN        S
..        ...  ...        ...    ...    ...      ...   ...      ...
886         0    1  27.000000      0      0  13.0000   NaN        S
887         1    1  19.000000      0      0  30.0000   B42        S
888         0    1  29.699118      1      2  23.4500   NaN        S
889         1    1  26.000000      0      0  30.0000  C148        C
890         0    1  32.000000      0      0   7.7500   NaN        Q

[891 rows x 8 columns]

In [70]:
df['Fare'].unique()

array([  7.25  ,  71.2833,   7.925 ,  53.1   ,   8.05  ,   8.4583,
        51.8625,  21.075 ,  11.1333,  30.0708,  16.7   ,  26.55  ,
        31.275 ,   7.8542,  16.    ,  29.125 ,  13.    ,  18.    ,
         7.225 ,  26.    ,   8.0292,  35.5   ,  31.3875, 263.    ,
         7.8792,   7.8958,  27.7208, 146.5208,   7.75  ,  10.5   ,
        82.1708,  52.    ,   7.2292,  11.2417,   9.475 ,  21.    ,
        41.5792,  15.5   ,  21.6792,  17.8   ,  39.6875,   7.8   ,
        76.7292,  61.9792,  27.75  ,  46.9   ,  80.    ,  83.475 ,
        27.9   ,  15.2458,   8.1583,   8.6625,  73.5   ,  14.4542,
        56.4958,   7.65  ,  29.    ,  12.475 ,   9.    ,   9.5   ,
         7.7875,  47.1   ,  15.85  ,  34.375 ,  61.175 ,  20.575 ,
        34.6542,  63.3583,  23.    ,  77.2875,   8.6542,   7.775 ,
        24.15  ,   9.825 ,  14.4583, 247.5208,   7.1417,  22.3583,
         6.975 ,   7.05  ,  14.5   ,  15.0458,  26.2833,   9.2167,
        79.2   ,   6.75  ,  11.5   ,  36.75  ,   7.7958,  12.5

In [72]:
df['Fare']

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...   
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64

In [78]:
df['Cabin']

0       NaN
1       C85
2       NaN
3      C123
4       NaN
       ... 
886     NaN
887     B42
888     NaN
889    C148
890     NaN
Name: Cabin, Length: 891, dtype: object

In [80]:
df['Cabin'].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64',

In [82]:
df['Cabin'] = df['Cabin'].ffill()

In [84]:
df

Survived  Sex        Age  SibSp  Parch     Fare Cabin Embarked
0           0    1  22.000000      1      0   7.2500   NaN        S
1           1    1  38.000000      1      0  71.2833   C85        C
2           1    1  26.000000      0      0   7.9250   C85        S
3           1    1  35.000000      1      0  53.1000  C123        S
4           0    1  35.000000      0      0   8.0500  C123        S
..        ...  ...        ...    ...    ...      ...   ...      ...
886         0    1  27.000000      0      0  13.0000   C50        S
887         1    1  19.000000      0      0  30.0000   B42        S
888         0    1  29.699118      1      2  23.4500   B42        S
889         1    1  26.000000      0      0  30.0000  C148        C
890         0    1  32.000000      0      0   7.7500  C148        Q

[891 rows x 8 columns]

In [86]:
df['Cabin'] = df['Cabin'].bfill()

In [88]:
df

Survived  Sex        Age  SibSp  Parch     Fare Cabin Embarked
0           0    1  22.000000      1      0   7.2500   C85        S
1           1    1  38.000000      1      0  71.2833   C85        C
2           1    1  26.000000      0      0   7.9250   C85        S
3           1    1  35.000000      1      0  53.1000  C123        S
4           0    1  35.000000      0      0   8.0500  C123        S
..        ...  ...        ...    ...    ...      ...   ...      ...
886         0    1  27.000000      0      0  13.0000   C50        S
887         1    1  19.000000      0      0  30.0000   B42        S
888         0    1  29.699118      1      2  23.4500   B42        S
889         1    1  26.000000      0      0  30.0000  C148        C
890         0    1  32.000000      0      0   7.7500  C148        Q

[891 rows x 8 columns]

In [90]:
df['Embarked']

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

In [92]:
df['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [94]:
df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [96]:
df['Embarked'] = df['Embarked'].fillna("S")

In [98]:
df

Survived  Sex        Age  SibSp  Parch     Fare Cabin Embarked
0           0    1  22.000000      1      0   7.2500   C85        S
1           1    1  38.000000      1      0  71.2833   C85        C
2           1    1  26.000000      0      0   7.9250   C85        S
3           1    1  35.000000      1      0  53.1000  C123        S
4           0    1  35.000000      0      0   8.0500  C123        S
..        ...  ...        ...    ...    ...      ...   ...      ...
886         0    1  27.000000      0      0  13.0000   C50        S
887         1    1  19.000000      0      0  30.0000   B42        S
888         0    1  29.699118      1      2  23.4500   B42        S
889         1    1  26.000000      0      0  30.0000  C148        C
890         0    1  32.000000      0      0   7.7500  C148        Q

[891 rows x 8 columns]

In [100]:
df['Embarked'].unique()

array(['S', 'C', 'Q'], dtype=object)