## SECTION 3 — Indexing & Slicing 

In [2]:
import numpy as np

In [4]:
a1 = np.array([[10,20,30],
               [40,50,60],
               [70,80,90]])

In [6]:
# 1. Basic Element Access
# For a matrix A[row, column]
a1[0,0]  # first row first col

10

In [8]:
a1[2,1]   # second row first col

80

In [10]:
a1[1,2]   # 1st row 2nd col

60

In [12]:
# 2. Selecting an Entire Row
a1[1]

array([40, 50, 60])

In [14]:
a1[1,:]

array([40, 50, 60])

In [20]:
a1[3] # index error will get if we try to fetch the row which is greter than the size of matrix

IndexError: index 3 is out of bounds for axis 0 with size 3

In [18]:
a1[2]

array([70, 80, 90])

In [22]:
# 3. Selecting an Entire Column
a1[:,1]

array([20, 50, 80])

In [24]:
a1[:,2]

array([30, 60, 90])

In [28]:
a1[:, 0]

array([10, 40, 70])

In [30]:
# 4. Slicing (start : end)
# a1[row_start : row_end, column_start : column_end]


In [34]:
a1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [32]:
a1[2:, 2:]

array([[90]])

In [40]:
# 50
a1[1:2, 1:2]

array([[50]])

In [56]:
#30
a1[:1, 2:3]

array([[30]])

In [58]:
# 5. Negative Indexing
a1[-1]  # last row

array([70, 80, 90])

In [60]:
a1[:, -1]  # last col

array([30, 60, 90])

In [62]:
# 6. Submatrix Extraction (Very Important)
 # i want this middle block
# 50,60
# 80,90

In [64]:
a1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [66]:
a1[1:3 , 1:3]

array([[50, 60],
       [80, 90]])

In [68]:
# [40, 50,]
# [70, 80,]
a1[1:3 , :2]

array([[40, 50],
       [70, 80]])

In [70]:
# SECTION 3 – Practice Questions
a2 = np.array([
    [3, 8, 9, 1],
    [4, 6, 7, 2],
    [5, 0, 3, 8],
    [9, 1, 4, 6]
])
a2

array([[3, 8, 9, 1],
       [4, 6, 7, 2],
       [5, 0, 3, 8],
       [9, 1, 4, 6]])

In [72]:
# a2[2, 3]
# Second row
# Third column
# Last row
# Last column
# Submatrix:
  #[[6, 7],
 #[0, 3]]
# First 2 rows & first 3 columns

In [110]:
a2[2,3]

8

In [92]:
# 2.
a2[2:3, :]

array([[5, 0, 3, 8]])

In [94]:
# 3.
a2[:, 3:4]

array([[1],
       [2],
       [8],
       [6]])

In [98]:
# 4.
a2[3:]

array([[9, 1, 4, 6]])

In [100]:
# 5.
a2[:, 3:]

array([[1],
       [2],
       [8],
       [6]])

In [102]:
# 6.submatrix 6,7,0,3
a2

array([[3, 8, 9, 1],
       [4, 6, 7, 2],
       [5, 0, 3, 8],
       [9, 1, 4, 6]])

In [104]:
a2[1:3, 1:3]

array([[6, 7],
       [0, 3]])

In [106]:
# 7.
a2[:2, :3]

array([[3, 8, 9],
       [4, 6, 7]])