## SECTION 4 — Reshape & Resize

In [1]:
import numpy as np

### Notes:
### Total elements must remain the same.
### Valid shapes for 12 elements: (3,4), (4,3), (2,6), (6,2), (12,1), (1,12).

In [5]:
matrix = np.arange(1,13)   # 1 d arr with 12 elements
arr = matrix.reshape(3,4)   # reshape to 3 rows and 4 columns
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
arr2 = matrix.reshape(4,3)
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
arr3 = matrix.reshape(2,6)
arr3

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [18]:
arr4 = matrix.reshape(12,1)
arr4

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [24]:
arr5 = matrix.reshape(1,12)
arr5

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

## 2. Flatten & ravel

### Flatten: Returns a 1D copy of the array.
### Ravel: Returns a 1D view (doesn’t copy data, saves memory).

### Use flatten when you want to modify independently.
### Use ravel when you just need a 1D view without extra memory.

In [32]:
flat = matrix.flatten()
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [64]:
a1 = np.arange(1, 25)
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [58]:
reshape = a1.reshape(6,4)

In [60]:
reshape

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [62]:
flat2 = reshape.flatten()
flat2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [66]:
flat2[20]

21

In [68]:
flat2[2]

3

In [74]:
a2 = np.random.randint(0, 20, (5,4))
a2

array([[11, 12, 16, 13],
       [17, 19, 10, 11],
       [15,  4, 15,  2],
       [19, 15,  3, 12],
       [17, 10,  8, 18]])

In [78]:
reshape2 = a2.reshape(4,5)
reshape2

array([[11, 12, 16, 13, 17],
       [19, 10, 11, 15,  4],
       [15,  2, 19, 15,  3],
       [12, 17, 10,  8, 18]])

In [82]:
flat3 = reshape2.flatten()
flat3

array([11, 12, 16, 13, 17, 19, 10, 11, 15,  4, 15,  2, 19, 15,  3, 12, 17,
       10,  8, 18])

In [89]:
#ravel

In [93]:
reveld = reshape2.ravel()
reveld

array([11, 12, 16, 13, 17, 19, 10, 11, 15,  4, 15,  2, 19, 15,  3, 12, 17,
       10,  8, 18])

In [101]:
reveld2 = reshape.ravel()
reveld2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

# 3. Resize

### Can change shape and the total number of elements.
### If new size > original, fills extra elements with zeros.

In [105]:
matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [107]:
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [109]:
reshape

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [123]:
reshape.resize((6,4))
print(reshape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [139]:
import numpy as np
mat = np.arange(1,13).reshape(4,3)
mat.resize((4,4))
print(mat)

ValueError: cannot resize this array: it does not own its data

In [ ]:
# it hase givrn the error because 
# the mat array deos not owns its data it creted from another array i.s (np.arange(1,13))
# numpy only allows when .resize() when if the array owns it memory block

In [141]:
# Why reshape doesn’t cause this error but resize does?
# ✔ reshape()
# Returns a new view or new array
# No memory change
# Safe
# ❗ resize()

# Changes the actual memory block
# Only allowed if array owns its data
# # Dangerous → modifies original array
# That’s why NumPy forbids resizing views.

In [143]:
# so solution is we can make a copy of it or can create direclty with full ownership

In [145]:
# like
mat = np.arange(1,13).reshape(4,3).copy()
print(mat)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [149]:
# or
mat2 = np.arange(1,13).reshape(4,3)
res = np.array(mat2)
print(res)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [161]:
result = np.resize(res , (4,6))
print(result)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]]


In [165]:
# SECTION 4 – Practice Questions
# Q1.
# Create a 1D array with 12 elements (1 → 12) and reshape it into:
# 3×4
# 4×3
# 2×6

# Q2.
# Flatten the 3×4 array to 1D.

# Q3.
# Resize the 3×4 array to 4×4 (observe new elements).

# # Q4.
# Create 1D array of 15 elements → reshape to 5×3 → then ravel it.

In [167]:
arr = np.arange(1,13)

In [169]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [171]:
reshape1 = arr.reshape(3,4)
reshape2 = arr.reshape(4,3)
reshape3 = arr.reshape(2,6)

In [175]:
reshape1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [177]:
reshape2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [179]:
reshape3

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [193]:
# 2.
flatan = reshape1.flatten()
flatan

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [197]:
res = np.resize(reshape1 , (4,5))
res

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12,  1,  2,  3],
       [ 4,  5,  6,  7,  8]])

In [199]:
arr2 = np.arange(1,16).reshape(5,3)

In [201]:
arr2.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])