### SECTION 2 — Array Creation Techniques

In [6]:
import numpy as np

In [10]:
# 1. np.zeros()
# Creates an array filled with 0.
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
# 2. np.ones()
# Creates an array filled with 1.
ones = np.ones((2,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
# 3. np.arange()
# Creates a range of values.
arange = np.arange(1, 10, 2)    # start = 1, stop = 10 , step = 2
arange

array([1, 3, 5, 7, 9])

In [28]:
# 4. np.linspace()
# Creates evenly spaced numbers between a range.
linspace = np.linspace(0,1,5)
linspace

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [34]:
# 5. np.eye()
# Creates an identity matrix.
# identity matrix means all principle diagonal elements are 1s and other are zero
eye = np.eye(4)
eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [44]:
# 6. Random Matrices
# Random integers:
random = np.random.randint(1,100, (3,3))   # from 1 to 100 and 3,3 matrix
random

array([[41, 93, 12],
       [47, 86, 79],
       [78, 76, 16]])

In [49]:
# Random normal distribution: 
random_dist = np.random.randn(3,3)
random_dist

array([[ 0.90004558, -0.75791683, -0.92984611],
       [-0.63263925,  0.08182989,  1.39316586],
       [-0.68083764, -0.42291977, -1.64735093]])

In [51]:
## SECTION 2 – Practice Questions

# Q1. Create a 4×4 matrix of zeros.
# Q2. Create numbers from 5 to 50 with step 5.
# Q3. Create a 3×3 identity matrix.
# Q4. Create a 5×5 matrix of random integers (1 to 20).
# Q5. Create 10 evenly spaced values between 0 and 5.

In [55]:
# 1
mat1 = np.zeros((4,4))
mat1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [59]:
# 2.
mat2 = np.arange(5,50,5)
mat2

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [63]:
# 3.
mat3 = np.eye(3,3)
mat3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
# 4.
mat4 = np.random.randint(1,20,(5,5))
mat4

array([[13, 15, 16, 18, 15],
       [ 2,  6,  1,  6, 17],
       [13,  7, 19, 18, 15],
       [13, 12, 18,  6,  1],
       [17,  5, 10,  1, 10]])

In [77]:
# 5.
mat5 = np.linspace(0,5,10)
mat5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])